name: strava_data_viz

dependencies:
    - python=3.5
    - pandas
    - pytables
    - seaborn
    - matplotlib
    - holoviews
    - datashader
    - xarray
    - geoviews
    - pip:
        - stravalib

